teleop_twist_joy_node:
  ros__parameters:
    axis_linear:  # Left thumb stick vertical
      x: 1
    scale_linear:
      x: 0.5 # 0.7 -> 0.1
    scale_linear_turbo:
      x: 1.0 # 1.5 -> 0.5

    axis_angular:  # Left thumb stick horizontal
      yaw: 0
    scale_angular:
      yaw: 0.03  #0.4 -> 0.8

    enable_button: 2  # Left trigger button
    enable_turbo_button: 5  # Right trigger button
